/// Flutter icons MyCustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyCustomIcons
///      fonts:
///       - asset: fonts/MyCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyCustomIcons {
  MyCustomIcons._();

  static const _kFontFam = 'MyCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData all_year = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distance = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fall = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fees = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData limited_access = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_fall = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_spring = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_summer = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData no_winter = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData park = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spring = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spring_fall = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData summer = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData summer_fall = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData summer_spring = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData winter = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData winter_fall = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData winter_spring = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData winter_summer = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duration_four = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duration_one = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duration_two = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
